#
# Copyright (C) 2024 Temmi Pietsch - All Rights Reserved
#
# You may not use, distribute or modify this code without the explicitly
# permission of the author.
#

trailingComma: all
useTabs: true
tabWidth: 4
semi: true
singleQuote: true
printWidth: 100
bracketSpacing: true
editor.formatOnSave: true
proseWrap: always
requireConfig: false
jsxBracketSameLine: false
